spring:
  profiles:
    active: local
  config:
    import:
      - 'classpath:adapter-http.yml'
      - 'classpath:adapter-persistence.yml'

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

